server:
  port: 8000
spring:
  application:
    name: sip-api-gaetway
  cloud:
    nacos:
      discovery:
        server-addr: ${BIZSIP_NACOS}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: sip-integrator
#          uri: lb://sip-integrator
#          predicates:
#            - Path=/api/**

logging:
  level:
    com.bizmda.bizsip: info
#  file:
#    name: ${BIZSIP_LOG_FILENAME}

graceful:
  shutdown:
    enabled: true