server:
  port: 8000
spring:
  application:
    name: sip-api-gaetway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: sip-integrator
#          uri: lb://sip-integrator
#          predicates:
#            - Path=/api/**

logging:
  level:
    com.bizmda.bizsip: debug

graceful:
  shutdown:
    enabled: true