server:
  port: 8001
spring:
  application:
    name: sip-sample-server
  cloud:
    nacos:
      discovery:
        server-addr: test.bizmda.com:8848

bizsip:
  config-path: /var/bizsip/config

logging:
  level:
    com.bizmda.bizsip: debug

graceful:
  shutdown:
    enabled: true