server:
  port: 8001
spring:
  application:
    name: sip-sample-server
  cloud:
    nacos:
      discovery:
        server-addr: test.bizmda.com:8848

bizsip:
  config-path: /Users/shizhengye/IdeaProjects/Biz-SIP-Cloud/sample/config

logging:
  level:
    com.bizmda.bizsip: debug