version: '3.1'
services:
  filebeat:
    image: elastic/filebeat:7.6.2
    container_name: filebeat
    volumes:
      - /bizsip:/bizsip
      - /root/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "logstash:139.198.177.218"

  api-gateway:
    build:
      context: ../api-gateway/target
      dockerfile: ../src/main/docker/Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/szhengye/bizsip:bizsip-api-gateway
    container_name: api-gateway
    volumes:
      - /bizsip:/bizsip
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/api-gateway.log
    env_file:
      - ./bizsip.env

  integrator:
    build:
      context: ../integrator/target
      dockerfile: ../src/main/docker/Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/szhengye/bizsip:bizsip-integrator
    container_name: integrator
    volumes:
      - /bizsip:/bizsip
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/integrator.log
    env_file:
      - ./bizsip.env


  dynamic-config:
    build:
      context: ../dynamic-config/target
      dockerfile: ../src/main/docker/Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/szhengye/bizsip:bizsip-dynamic-config
    container_name: dynamic-config
    volumes:
      - /bizsip:/bizsip
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/dynamic-config.log
    env_file:
      - ./bizsip.env

  sample-client:
    build:
      context: ../sample/sample-client/target
      dockerfile: ../src/main/docker/Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/szhengye/bizsip:bizsip-sample-client
    container_name: sample-client
    volumes:
      - /bizsip:/bizsip
    ports:
      - 8081:8080
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/sample-client.log
    env_file:
      - ./bizsip.env

  sample-server:
    build:
      context: ../sample/sample-server/target
      dockerfile: ../src/main/docker/Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/szhengye/bizsip:bizsip-sample-server
    container_name: sample-server
    volumes:
      - /bizsip:/bizsip
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/sample-server.log
    env_file:
      - ./bizsip.env

  netty-client-adaptor:
    build:
      context: ../client-adaptor/netty-client-adaptor/target
      dockerfile: ../src/main/docker/Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/szhengye/bizsip:bizsip-netty-client-adaptor
    container_name: netty-client-adaptor
    volumes:
      - /bizsip:/bizsip
    ports:
      - 10002:10002
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/netty-client-adaptor.log
    env_file:
      - ./bizsip.env

  bizsip-admin-app:
    image: bizsip/admin-app:latest
    container_name: bizsip-admin-app
    volumes:
      - /bizsip:/bizsip
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/bizsip-admin.log
    env_file:
      - ./bizsip.env

  bizsip-admin-web:
    image: bizsip/admin-web:latest
    container_name: bizsip-admin-web
    ports:
      - 80:80
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "jeecg-boot-system:106.12.61.145"
