version: '3.1'
services:
#  logstash:
#    restart: always
#    image: logstash:7.6.2
#    container_name: logstash
#    volumes:
#      - /bizsip:/bizsip
#    environment:
#      TZ: Asia/Shanghai
#    ports:
#      - 5044:5044
#    extra_hosts:
#      - "elasticsearch:139.198.177.218"

  filebeat:
#    restart: always
    image: elastic/filebeat:7.6.2
    container_name: filebeat
    volumes:
      - /bizsip:/bizsip
      - /root/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "logstash:139.198.177.218"

  api-gateway:
    build:
      context: ../api-gateway/target
      dockerfile: ../src/main/docker/Dockerfile
#    restart: always
    image: bizsip/api-gateway:latest
    container_name: api-gateway
    volumes:
      - /bizsip/config:/bizsip/config
      - /bizsip/logs:/logs
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/api-gateway.log
    env_file:
      - ./bizsip.env

  integrator:
    build:
      context: ../integrator/target
      dockerfile: ../src/main/docker/Dockerfile
#    restart: always
    image: bizsip/integrator:latest
    container_name: integrator
    volumes:
      - /bizsip/config:/bizsip/config
      - /bizsip/logs:/logs
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/integrator.log
    env_file:
      - ./bizsip.env


#  dynamic-config:
#    build:
#      context: ../dynamic-config/target
#      dockerfile: ../src/main/docker/Dockerfile
#    restart: always
#    image: bizsip/dynamic-config:latest
#    container_name: dynamic-config
#    volumes:
#      - /bizsip/config:/bizsip/config
#      - /bizsip/logs:/logs
#    environment:
#      TZ: Asia/Shanghai
#      BIZSIP_LOG_FILENAME: /bizsip/logs/dynamic-config.log
#    env_file:
#      - ./bizsip.env

#  sample-client:
#    build:
#      context: ../sample/sample-client/target
#      dockerfile: ../src/main/docker/Dockerfile
#    restart: always
#    image: bizsip/sample-client:latest
#    container_name: sample-client
#    volumes:
#      - /bizsip/config:/bizsip/config
#      - /bizsip/logs:/logs
#    ports:
#      - 8081:8080
#    environment:
#      TZ: Asia/Shanghai
#      BIZSIP_LOG_FILENAME: /bizsip/logs/sample-client.log
#    env_file:
#      - ./bizsip.env

  sample-server:
    build:
      context: ../sample/sample-server/target
      dockerfile: ../src/main/docker/Dockerfile
#    restart: always
    image: bizsip/sample-server:latest
    container_name: sample-server
    volumes:
      - /bizsip/config:/bizsip/config
      - /bizsip/logs:/logs
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/sample-server.log
    env_file:
      - ./bizsip.env

  netty-client-adaptor:
    build:
      context: ../client-adaptor/netty-client-adaptor/target
      dockerfile: ../src/main/docker/Dockerfile
#    restart: always
    image: bizsip/netty-client-adaptor:latest
    container_name: netty-client-adaptor
    volumes:
      - /bizsip/config:/bizsip/config
      - /bizsip/logs:/logs
    ports:
      - 10002:10002
    environment:
      TZ: Asia/Shanghai
      BIZSIP_LOG_FILENAME: /bizsip/logs/netty-client-adaptor.log
    env_file:
      - ./bizsip.env

#  bizsip-admin:
#    restart: always
#    image: bizsip/admin:latest
#    container_name: bizsip-admin
#    volumes:
#      - /bizsip:/bizsip
#      - /bizsip/config:/bizsip/config
#      - /bizsip/logs:/logs
#    ports:
#      - 8080:8080
#    environment:
#      TZ: Asia/Shanghai
#      BIZSIP_LOG_FILENAME: /bizsip/logs/bizsip-admin.log

#  bizsip-nginx:
#    restart: always
#    image: bizsip/nginx:latest 
#    container_name: bizsip-nginx
#    ports:
#      - 80:80
#    environment:
#      TZ: Asia/Shanghai
#    extra_hosts:
#      - "jeecg-boot-system:106.12.61.145"

