server:
  port: 8088
spring:
  application:
    name: sip-dynamic-config
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

bizsip:
  config-path: /Users/shizhengye/IdeaProjects/Biz-SIP-Cloud/sample/config
