server:
  port: 8088
spring:
  application:
    name: sip-dynamic-config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

bizsip:
  config-path: /var/bizsip/config

logging:
  level:
    com.bizmda.bizsip: debug

graceful:
  shutdown:
    enabled: true