server:
  port: 8080

spring:
  application:
    name: sip-rest-client-adaptor
  cloud:
    nacos:
      discovery:
        server-addr: ${BIZSIP_NACOS}

bizsip:
  config-path: ${BIZSIP_CONFIG}
  integrator-url: http://sip-integrator/api/
  client-adaptor-id: client1

logging:
  level:
    com.bizmda.bizsip: info
  file:
    name: ${BIZSIP_LOG_FILENAME}

graceful:
  shutdown:
    enabled: true