server:
  port: 8080

spring:
  application:
    name: sip-rest-client-adaptor
  cloud:
    nacos:
      discovery:
        server-addr: test.bizmda.com:8848

bizsip:
  config-path: /var/bizsip/config
  integrator-url: http://sip-integrator/api/
  client-adaptor-id: client1

logging:
  level:
    com.bizmda.bizsip: info

graceful:
  shutdown:
    enabled: true