server:
  port: 8090

spring:
  application:
    name: sip-netty-client-adaptor
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

bizsip:
  config-path: /Users/shizhengye/IdeaProjects/Biz-SIP-Cloud/sample/config
  integrator-url: http://sip-integrator/api/
  client-adaptor-id: client1

logging:
  level:
    com.bizmda.bizsip: debug

netty:
  port: 10002