server:
  port: 8090

spring:
  application:
    name: sip-netty-client-adaptor
  cloud:
    nacos:
      discovery:
        server-addr: ${BIZSIP_NACOS:127.0.0.1:8848}

bizsip:
  config-path: ${BIZSIP_CONFIG:/bizsip/config}
  integrator-url: http://sip-integrator/api/
  client-adaptor-id: client1

netty:
  port: ${BIZSIP_NETTY_PORT:10002}

logging:
  level:
    com.bizmda.bizsip: debug
  file:
    name: ${BIZSIP_LOG_FILENAME}

graceful:
  shutdown:
    enabled: true