- id: server1
  type: rest
  url: http://127.0.0.1:8001/server1
  message:
    type: simple-xml
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server1.controller.Server1

- id: server2
  type: rest
  url: http://127.0.0.1:8002/server2
  message:
    type: velocity-json
    pack-rules:
      - predicate: '#{#data[flag]==2}'
        rule: /server2/1.vm
      - predicate:
        rule: server1/pack/error
    unpack-rules:
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server2.controller.Server2