- id: server1
  type: rest
  url: http://sip-sample-server/server1
  message:
    type: simple-json
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.CrmServer

- id: server2
  type: rest
  url: http://sip-sample-server/server2
  message:
    type: simple-json
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.ActServer

- id: server3
  type: rest
  url: http://sip-sample-server/server3
  message:
    type: simple-xml
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.EchoServer

- id: server4
  type: rest
  url: http://sip-sample-server/server4
  message:
    type: velocity-json
    pack-rules:
      - predicate: '#{#data[sex]=="0"}'
        rule: server4/woman.vm
      - predicate: '#{#data[sex]=="1"}'
        rule: server4/man.vm
      - predicate:
        rule: server4/error.vm
    unpack-rules:
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.EchoServer

- id: server5
  type: rest
  url: http://sip-sample-server/server5
  message:
    type: velocity-xml
    pack-rules:
      - predicate: '#{#data[sex]=="0"}'
        rule: server5/woman.vm
      - predicate: '#{#data[sex]=="1"}'
        rule: server5/man.vm
      - predicate:
        rule: server5/error.vm
    unpack-rules:
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.EchoServer

- id: server6
  type: rest
  url: http://sip-sample-server/server6
  message:
    type: fixed-length
    pre-unpack:
      - name: sex
        length: 1
        functions:
          - name: trim
    pack-rules:
      - predicate: '#{#data[sex]=="0"}'
        rule: server6/woman.yml
      - predicate: '#{#data[sex]=="1"}'
        rule: server6/man.yml
      - predicate:
        rule: server6/error.yml
    unpack-rules:
      - predicate: '#{#data[sex]=="0"}'
        rule: server6/woman.yml
      - predicate: '#{#data[sex]=="1"}'
        rule: server6/man.yml
      - predicate:
        rule: server6/error.yml
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.EchoServer

- id: server7
  type: rest
  url: http://sip-sample-server/server7
  message:
    type: velocity-split
    separators:
      - "*"
      - ","
    pack-rules:
      - predicate: '#{#data[sex]=="0"}'
        rule: server7/woman.vm
      - predicate: '#{#data[sex]=="1"}'
        rule: server7/man.vm
      - predicate:
        rule: server7/error.vm
  protocol:
    type: java
    class-name: com.bizmda.bizsip.sample.serveradaptor.server.controller.EchoServer

- id: netty
  type: rest
  url: http://sip-sample-server/netty
  message:
    type: simple-json
  protocol:
    type: netty
    host: 127.0.0.1
    port: 10001
